### PR TITLE
Filter documents using wildcards

### PR DESCRIPTION
**Pull request by JamieCressey**
This PR adds the ability to filter documents using wildcards. E.g.

```
>>>TestDocument.objects().filter({'name':'G*'})

[<TestDocument: George:2>]
```

It also includes a few PEP8 fixups.

### CODE REVIEW

**Comment by JamieCressey** [comment]
Looks like some environment vars might be missing from the CI tests;

`TypeError: int() argument must be a string or a number, not 'NoneType'`

They pass locally.

**Comment by bjinwright** [comment]
I'm looking into the CI errors now

**Comment by bjinwright** [comment]
For some reason the secret environment variables are not loading in Travis on that branch.

**Comment by bjinwright** [comment]
For some reason, it wouldn't work as a pull request but worked after I merged it into the develop branch.

**Pull request merged**
